site_name: Poema Network
theme:
    name: flatly
extra_css:
    - css/hidefooter.css
markdown_extensions:
    - pymdownx.tilde
site_url: https://net.kskb.moe/
repo_url: https://github.com/KSKBpage/PoemaNetwork
edit_uri: edit/main/docs/