site_name: Poema Network
theme:
  # name: material
  name: flatly
  custom_dir: static
extra_css:
    - css/hidefooter.css
markdown_extensions:
  - pymdownx.tilde
  - pymdownx.extra
  - pymdownx.magiclink
nav:
  - Poema Network: index.md
  - Poema-IX: "https://ix.poema.eu.org"
  - KSKB-Net(DN42): "https://dn42.kskb.eu.org"
site_url: https://net.kskb.moe/
repo_url: https://github.com/KSKBpage/PoemaNetwork
edit_uri: blob/main/docs/