site_name: Poema Network
theme:
  name: material
  # name: flatly
extra_css:
    - css/hidefooter.css
markdown_extensions:
  - pymdownx.tilde
  - pymdownx.extra
nav:
  - Poema Network: index.md
  - KSKB-IX: "https://ix.kskb.eu.org"
site_url: https://net.kskb.moe/
repo_url: https://github.com/KSKBpage/PoemaNetwork
edit_uri: edit/main/docs/